# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99289bf637cd2d1ac981c321434ca11ed3cedd5dca05268d5fe810d8ca0c59fd79ad2e48538d18516f47e947d7a1e9f815f8a29d8cd211b352d2fc0fa6e1d0c1

test:
  secret_key_base: 3f5db7d974ea130cb0e0ce532572aa5b443ece2d9d637e889703b7f96a59192a658bba32aaff9cfd5b179a76e0268b79b6a76b78adb7f00ee7164fb6bca7fb56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
